---
title: "Growth in constant environments"
author: Thomas Julou
date: "`r format(Sys.time(), '%d %B, %Y')`"
---


Let's compute stats over the cell cycle for each cell.

```{r}
mycells_constant <- filter(myframes, condition %in% c('glucose', 'lactose'), !discard_top) %>%
  filter(!(date=='20160427' & time_sec>7e4)) %>%  # remove dilution step at the end of expt
  # group_by(condition, date, pos, gl, id, cell, parent_id, genealogy) %>%
  partition(condition, date, pos, gl, id, cell, parent_id, genealogy, cluster=mycluster) %>%
  filter(!any(discard_start), end_type=='div') %>% # full cell cycles only
  filter(n()>4) %>% # at least 4 time points
  do((function(.df) {
    # browser()
    
    .mod_ll_t <- lm( log(length_um)~time_sec, .df)  # use fastLm() for predict
    # .mod_ll_t <- fastLmPure( cbind(1, .df$time_sec), log(.df$length_um) )
    .mod_lg_t <- fastLmPure( cbind(1, .df$time_sec), log(.df$gfp_nb) )
    .mod_l_t <- fastLmPure( cbind(1, .df$time_sec), .df$length_um )
    .mod_g_t <- fastLmPure( cbind(1, .df$time_sec), .df$gfp_nb )
    .mod_g_l <- fastLmPure( cbind(1, .df$length_um), .df$gfp_nb )

    .time_birth <- first(.df$time_sec)
    .time_div <- last(.df$time_sec)
    .logl <- predict(.mod_ll_t, se.fit=TRUE)
    data.frame(npoints=.mod_ll_t$df.residual+1,
               time_birth=.time_birth, time_div=.time_div, 
               cell_num_from_top=mean(.df$cell_num_in_lane),
               cell_num_from_bottom=mean(.df$total_cell_in_lane-.df$cell_num_in_lane), 
               loglength_start=first(.logl$fit), loglength_startse=first(.logl$se.fit), 
               loglength_end=last(.logl$fit), loglength_endse=last(.logl$se.fit), 
               logl_time_slope=.mod_ll_t$coefficients[2], logl_time_slopesd=summary(.mod_ll_t)$coefficients[2,2], 
               # logl_time_slope=.mod_ll_t$coefficients[2], logl_time_slopesd=.mod_ll_t$stderr[2], 
               logl_time_r2=cor(.df$time_sec, log(.df$length_um))^2,
               logg_time_slope=.mod_lg_t$coefficients[2], logg_time_slopesd=.mod_lg_t$stderr[2], 
               logg_time_r2=cor(.df$time_sec, log(.df$gfp_nb))^2,
               l_time_slope=.mod_l_t$coefficients[2], l_time_slopesd=.mod_l_t$stderr[2], 
               l_time_r2=cor(.df$time_sec, .df$length_um)^2,
               g_first=first(.df$gfp_nb), g_last=last(.df$gfp_nb),
               g_time_slope=.mod_g_t$coefficients[2], g_time_slopesd=.mod_g_t$stderr[2], 
               g_time_r2=cor(.df$time_sec, .df$gfp_nb)^2,
               g_l_slope=.mod_g_l$coefficients[2], g_l_slopesd=.mod_g_l$stderr[2], 
               g_l_r2=cor(.df$length_um, log(.df$gfp_nb))^2)
  })(.) ) %>% 
  collect() %>% 
  arrange(condition, date, pos, gl, id) %>% 
  mutate(gl_id=gsub('\\.[0-9]+$', '', cell))

myframes_constant <- semi_join(myframes, mycells_constant) %>% 
  # group_by(date, pos, gl, id) %>% 
  partition(date, pos, gl, id, cluster=mycluster) %>%
  do((function(.df){
    .n <- dim(.df)[1]
      .cell_cycle <- ((1:.n)-.5) / .n
      .mod_ll_t <- lm( log(length_um)~time_sec, .df)  # use lm() for predict with se
      .pred_ll <- predict(.mod_ll_t, se.fit=TRUE)
      .logl <- .pred_ll$fit
    mutate(.df, cell_cycle=.cell_cycle, length_predict=exp(.logl))
  })(.)) %>% 
  collect()

```



## Heritability of various life history traits

```{r}
mycells_constant <- mycells_constant %>% 
  mutate(alpha=logl_time_slope, dt=log(2)/alpha, 
         l_birth=exp(loglength_start), l_div=exp(loglength_end),
         c_birth=g_first/l_birth, c_div=g_last/l_div)

mypairs_constant <- mycells_constant %>% 
  # group_by(str_cond, gl_id) %>%
  partition(condition, date, gl_id, 
            cluster=mycluster %>% cluster_assign_func(genealogy_relationship, genealogy_ontology) ) %>% 
  do((function(.df) {
    # browser()
    if (nrow(.df)<2) 
      return(data.frame())
    return( combn(.df$genealogy, 2, simplify=FALSE) %>% 
      lapply(function(.x) as.data.frame(genealogy_relationship(.x), stringsAsFactors=FALSE)) %>% 
      do.call(rbind, .) )
  })(.)) %>% 
  collect() %>% 
  left_join(mycells_constant %>% ungroup %>% 
              select(gl_id, genealogy, alpha, dt, l_birth, l_div, c_birth, c_div) %>%
              rename(genealogy_1=genealogy) %>% 
              gather(variable, value_1, -gl_id, -genealogy_1) ) %>% 
  left_join(mycells_constant %>% ungroup %>% 
              select(gl_id, genealogy, alpha, dt, l_birth, l_div, c_birth, c_div) %>%
              rename(genealogy_2=genealogy) %>% 
              gather(variable, value_2, -gl_id, -genealogy_2) ) %>% 
  mutate(variable=factor(variable, levels=unique(variable)),
         rel=factor(rel, levels=c("sisters", "cousins1", "cousins2", "niece")))

# ggplot(mycellpairs %>% ungroup %>% sample_n(1e5), aes(value_1, value_2, col=factor(rel))) +
#   facet_wrap(~str_cond+variable, scales='free') +
#   geom_point(alpha=.5, size=.5) +
#   expand_limits(x=0, y=0)

mypairs_constant %>% 
group_by(condition, variable, div_min, div_max) %>% 
  summarise(r2=cor(value_1,  value_2, use="complete.obs", method="pearson")^2, n=n()) %>% 
  mutate(rel=(Vectorize(genealogy_ontology))(div_min, div_max)) %>% 
  (function(.df) ggplot(.df, aes(div_min, div_max)) +
     facet_grid(condition~variable) +
     geom_tile(aes(fill=r2), stat='identity', show.legend=FALSE) +
     geom_text(aes(label=sprintf("%s\nr2 = %.3f", rel, r2)), size=2) +
     geom_text(aes(y=div_max-.4, label=sprintf("(n = %d)", n)), size=1.5) +
     # scale_fill_gradient(high=plotwidgets::modCol('red', darken=-.3), low=plotwidgets::modCol('blue', darken=-.3)) +
     scale_fill_distiller(palette="Spectral", direction=-1) +
     scale_x_continuous(breaks=0:10, expand=c(0,0)) + scale_y_continuous(trans="reverse", breaks=0:10, expand=c(0,0)) +
     expand_limits(fill=0) + coord_fixed() +
     labs(x='divs since common ancestor (cell 1)', y='div since common ancestor (cell 2)')
  )

last_plot() +
  scale_fill_distiller(palette="Spectral", limits=c(0, .5), direction=-1, na.value="grey95")
# ggsave('Rplot.pdf', width=10, height=8)

```


```{r}
mypairs_constant %>% 
  filter(div_min==div_max) %>% 
  group_by(condition, variable, rel) %>% 
  summarise(r2=cor(value_1,  value_2, use="complete.obs", method="pearson")^2, n=n()) %>% 
  ggplot(aes(variable, r2)) +
  facet_wrap(~condition) +
  geom_bar(aes(fill=rel), stat='identity', pos='dodge') +
  geom_text(aes(y=1, label=sprintf("(n = %d)", n), group=rel), 
            angle=90, hjust=1, pos=position_dodge(width=0.8)) +
  theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
        legend.position='top')
# ggsave('Rplot.pdf', width=7, height=5)

```


## Fluo in glucose

```{r}
myframes_constant %>% 
  filter(condition=='glucose') %>% 
  filter(!discard_start, !discard_top) %>%  
  ggplot(aes(gfp_nb, 1-..y..)) +
  stat_ecdf(aes(col='ASC662\n(LacZ-GFP)', lty='glucose', group=date)) +
  stat_ecdf(aes(col='MG1655', lty=medium),
    data=myframes %>% ungroup %>% filter(!discard_start, !discard_top, condition=='mg1655', time_sec>m_start+2*3600)) +
  stat_ecdf(aes(col=condition, lty='glucose'), data=myframes %>% ungroup %>% 
              filter(!discard_start, !discard_top, medium=='glucose+IPTG', m_cycle==1,
                     condition %in% c('switch_withIPTG1uM', 'switch_withIPTG5uM')) ) +
  labs(x='GFP level (molecules)', y='reverse cumulative probability', col='strain', lty='medium') +
  coord_cartesian(xlim=c(-100, 150))

```


